apiVersion: v1
kind: Pod
metadata:
  name: requestslimitspod
spec:
  containers:
    - name: webserver
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "0.5"
        limits:
          memory: "128Mi"
          cpu: "1"