apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
    - name: webserver
      image: nginx
      tty: true
      livenessProbe:
        exec:
          command:
            - service
            - nginx
            - status
        initialDelaySeconds: 20
        periodSeconds: 5