apiVersion: v1
kind: Pod
metadata:
  name: readiness
spec:
  containers:
    - name: webserver
      image: ubuntu
      tty: true
      readinessProbe:
        exec:
          command:
            - ls
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5