apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    name: webserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  strategy: 
    type: Recreate
  template:
    metadata:
      name: webserver-pod
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx