apiVersion: v1
kind: Pod
metadata:
  name: envsecret
spec:
  containers:
    - name: envsecret
      image: nginx
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: firstsecret
              key: dbpass
  restartPolicy: Never
