apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    name: webserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: webserver-pod
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
      